<?php

namespace App\Facades\PatientService;

use App\Models\PatientHeader;
use Illuminate\Support\Facades\Facade;

/**
 * @method static array mapPatientModel(PatientHeader $patientHeader)
 * @method static array getPatients(?\App\Models\User $user = null)
 */
class PatientHeaderService extends Facade
{
    protected static function getFacadeAccessor(): string
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'PatientHeaderService';
    }
}
