<?php

namespace App\Facades\PatientService;

use App\Models\PatientTest;
use Illuminate\Support\Facades\Facade;

/**
 * @method static array mapTestModel(PatientTest $test)
 */
class PatientTestService extends Facade
{
    protected static function getFacadeAccessor(): string
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'patientTestService';
    }
}
